---

- name: Download the cloudwatch logs agent
  get_url:
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
    dest: /tmp/awslogs-agent-setup.py
    mode: 0750

- name: Create /tmp/awslogs.conf
  copy:
    src: awslogs.conf
    dest: /tmp/awslogs.conf
    owner: root
    group: root
    mode: 0600

- name: Run awslogs agent setup
  command: "/tmp/awslogs-agent-setup.py -n -r {{ec2_region | default('us-east-1')}} -c /tmp/awslogs.conf"
